version: '2'

services:
  frontend:
    build:
      context: .
      dockerfile: ./client/docker/development.dockerfile
    environment:
      PORT: 3100
      NODE_ENV: development
      API: http://localhost:4100
      SERVER_API_GQL: http://172.29.0.3:4100/graphql
      BROWSER_API_GQL: http://localhost:4100/graphql
      HOST: http://localhost:3100
    ports:
      - 3100:3100
    links:
      - backend
    volumes:
      - ./client/:/usr/src/app/
      - /usr/src/app/node_modules
    networks:
      vpcbr:
        ipv4_address: 172.29.0.2
  backend:
    build:
     context: .
     dockerfile: ./server/dockerfiles/development.dockerfile
    environment:
      API_PORT: 4100
      MONGO_HOST: db
      MONGO_PORT: 27017
      DB_NAME: blog
      JWT_SECRET: 64HIHC10RGW%GJ<
    depends_on:
      - db
    ports:
      - 4100:4100
    networks:
      vpcbr:
        ipv4_address: 172.29.0.3
    volumes:
      - ./server/:/usr/src/app/
      - ./server/public/:/usr/src/app/public/
      - /usr/src/app/node_modules
  db:
    image: mongo
    volumes:
      - './data:/data/db'
    networks:
      vpcbr:
        ipv4_address: 172.29.0.4
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
       - subnet: 172.29.0.0/16
