version: "2"

services:
  frontend:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      PORT: 3100
      NODE_ENV: production
    ports:
      - 3100:3100
    links:
      - backend
  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      API_PORT: 4100
      MONGO_HOST: db
      MONGO_PORT: 27017
      DB_NAME: blog
      JWT_SECRET: 64HIHC10RGW%GJ<
    depends_on:
      - db
    ports:
      - 4100:4100
    volumes:
      - ./server/public/:/usr/src/app/public/
  db:
    image: mongo
    volumes:
      - "/root/data:/data/db"
