version: '2'

services:
  frontend:
    build:
      context: .
      dockerfile: ./client/docker/production.dockerfile
    environment:
      PORT: 3100
      NODE_ENV: production
      API: http://apiblog.sonnemon.quanticotrends.com
      SERVER_API_GQL: http://apiblog.sonnemon.quanticotrends.com/graphql
      BROWSER_API_GQL: http://apiblog.sonnemon.quanticotrends.com/graphql
      HOST: http://blog.sonnemon.com
    ports:
      - 3100:3100
    links:
      - backend
  backend:
    build:
     context: .
     dockerfile: ./server/dockerfiles/production.dockerfile
    environment:
      API_PORT: 4100
      MONGO_HOST: db
      MONGO_PORT: 27017
      DB_NAME: blog
      JWT_SECRET: 64HIHC10RGW%GJ<
    depends_on:
      - db
    ports:
      - 4100:4100
  db:
    image: mongo
    volumes:
      - './data:/data/db'
